# Generated by Django 4.2.23 on 2025-08-06 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="客户姓名")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="电话及微信号"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "客户",
                "verbose_name_plural": "客户",
            },
        ),
        migrations.CreateModel(
            name="MonthlyPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_date", models.DateField(verbose_name="出款时间")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="出款金额"
                    ),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=100, verbose_name="备注"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.customer",
                        verbose_name="客户",
                    ),
                ),
            ],
            options={
                "verbose_name": "月供出款记录",
                "verbose_name_plural": "月供出款记录",
            },
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank", models.CharField(max_length=50, verbose_name="银行渠道")),
                (
                    "total_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="总授信额度",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="贷款余额",
                    ),
                ),
                (
                    "monthly_payment",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="月还款",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="到期时间"),
                ),
                (
                    "repayment_date",
                    models.DateField(blank=True, null=True, verbose_name="还款日"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.customer",
                        verbose_name="客户",
                    ),
                ),
            ],
            options={
                "verbose_name": "信用贷款账单明细",
                "verbose_name_plural": "信用贷款账单明细",
            },
        ),
        migrations.CreateModel(
            name="CreditCardPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank", models.CharField(max_length=50, verbose_name="银行")),
                ("payment_date", models.DateField(verbose_name="出款时间")),
                (
                    "payment_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="出款金额"
                    ),
                ),
                (
                    "withdrawal_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="刷出金额",
                    ),
                ),
                (
                    "withdrawal_date",
                    models.DateField(blank=True, null=True, verbose_name="刷出时间"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.customer",
                        verbose_name="客户",
                    ),
                ),
            ],
            options={
                "verbose_name": "信用卡出款记录",
                "verbose_name_plural": "信用卡出款记录",
            },
        ),
        migrations.CreateModel(
            name="CreditCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank", models.CharField(max_length=50, verbose_name="银行渠道")),
                (
                    "total_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="总授信额度",
                    ),
                ),
                (
                    "has_installment",
                    models.BooleanField(default=False, verbose_name="有无分期"),
                ),
                (
                    "installment_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="分期金额",
                    ),
                ),
                (
                    "billing_date",
                    models.DateField(blank=True, null=True, verbose_name="账单日"),
                ),
                (
                    "repayment_date",
                    models.DateField(blank=True, null=True, verbose_name="还款日"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.customer",
                        verbose_name="客户",
                    ),
                ),
            ],
            options={
                "verbose_name": "信用卡账单明细",
                "verbose_name_plural": "信用卡账单明细",
            },
        ),
    ]
