# Generated by Django 4.2.23 on 2025-08-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditcard",
            name="billing_date",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="账单日"
            ),
        ),
        migrations.AlterField(
            model_name="creditcard",
            name="repayment_date",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="还款日"
            ),
        ),
        migrations.AlterField(
            model_name="creditcardpayment",
            name="withdrawal_date",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="刷出时间"
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="repayment_date",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="还款日"
            ),
        ),
    ]
