# Generated by Django 4.2.23 on 2025-08-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_creditcard_billing_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditcard",
            name="installment_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=12,
                null=True,
                verbose_name="分期金额",
            ),
        ),
        migrations.AlterField(
            model_name="creditcard",
            name="total_limit",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=12,
                null=True,
                verbose_name="总授信额度",
            ),
        ),
        migrations.AlterField(
            model_name="creditcardpayment",
            name="payment_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="出款金额",
            ),
        ),
        migrations.AlterField(
            model_name="creditcardpayment",
            name="withdrawal_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=12,
                null=True,
                verbose_name="刷出金额",
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="balance",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=12,
                null=True,
                verbose_name="贷款余额",
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="monthly_payment",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=12,
                null=True,
                verbose_name="月还款",
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="total_limit",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=12,
                null=True,
                verbose_name="总授信额度",
            ),
        ),
    ]
