# Generated by Django 4.2.23 on 2025-08-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_creditcardpayment_payment_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditcardpayment",
            name="payment_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=12,
                null=True,
                verbose_name="出款金额",
            ),
        ),
    ]
