# Generated by Django 4.2.23 on 2025-08-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_creditcardpayment_payment_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monthlypayment",
            name="amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="出款金额",
            ),
        ),
    ]
