# Generated by Django 4.2.23 on 2025-08-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_monthlypayment_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditcardpayment",
            name="payment_date",
            field=models.DateField(blank=True, null=True, verbose_name="出款时间"),
        ),
        migrations.AlterField(
            model_name="creditcardpayment",
            name="withdrawal_date",
            field=models.DateField(blank=True, null=True, verbose_name="刷出时间"),
        ),
    ]
