# Generated by Django 4.2.23 on 2025-08-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_creditcardpayment_payment_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditcardpayment",
            name="fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=12,
                null=True,
                verbose_name="信用卡费率(3%)",
            ),
        ),
        migrations.AddField(
            model_name="creditcardpayment",
            name="notes",
            field=models.CharField(blank=True, max_length=200, verbose_name="备注"),
        ),
        migrations.AddField(
            model_name="monthlypayment",
            name="cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=12,
                null=True,
                verbose_name="资金使用成本",
            ),
        ),
        migrations.AddField(
            model_name="monthlypayment",
            name="days_used",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="资金使用天数"
            ),
        ),
        migrations.AddField(
            model_name="monthlypayment",
            name="is_private",
            field=models.BooleanField(default=False, verbose_name="是否私人借款"),
        ),
        migrations.AlterField(
            model_name="monthlypayment",
            name="notes",
            field=models.CharField(blank=True, max_length=200, verbose_name="备注"),
        ),
    ]
