# Generated by Django 4.2.23 on 2025-08-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_creditcardpayment_fee_creditcardpayment_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="financing_date",
            field=models.DateField(blank=True, null=True, verbose_name="融资日期"),
        ),
    ]
