# Generated by Django 4.2.23 on 2025-08-13 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_company_customer_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="contract_date",
            field=models.DateField(blank=True, null=True, verbose_name="签约日期"),
        ),
        migrations.AddField(
            model_name="customer",
            name="last_reminder_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="上一次提醒日期"
            ),
        ),
    ]
