# Generated by Django 4.2.24 on 2025-09-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_customer_contract_date_customer_last_reminder_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="credit_card_multiplier",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=1.0,
                max_digits=5,
                null=True,
                verbose_name="信用卡倍率",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="monthly_payment_multiplier",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=1.0,
                max_digits=5,
                null=True,
                verbose_name="月供倍率",
            ),
        ),
    ]
