# Generated by Django 4.2.24 on 2025-09-28 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_customer_credit_card_multiplier_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditcardpayment",
            name="fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=12,
                null=True,
                verbose_name="信用卡费率",
            ),
        ),
        migrations.CreateModel(
            name="CustomerImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="图片标题"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="customer_images/", verbose_name="图片文件"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.customer",
                        verbose_name="客户",
                    ),
                ),
            ],
            options={
                "verbose_name": "客户图片",
                "verbose_name_plural": "客户图片",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
