# Generated by Django 4.2.24 on 2025-09-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_creditcardpayment_fee_customerimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="credit_card_multiplier",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.002,
                max_digits=5,
                null=True,
                verbose_name="信用卡倍率",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="monthly_payment_multiplier",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.003,
                max_digits=5,
                null=True,
                verbose_name="月供倍率",
            ),
        ),
    ]
