# Generated by Django 4.2.24 on 2025-09-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_customer_credit_card_multiplier_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="credit_card_multiplier",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.003,
                max_digits=5,
                null=True,
                verbose_name="信用卡倍率",
            ),
        ),
    ]
