# Generated by Django 4.2.24 on 2025-09-28 07:38

from django.db import migrations


def reset_multiplier_fields(apps, schema_editor):
    Customer = apps.get_model('core', 'Customer')
    # 将所有客户的倍率字段重置为None，这样会使用模型的新默认值
    Customer.objects.update(
        credit_card_multiplier=None,
        monthly_payment_multiplier=None
    )


def reverse_reset_multiplier_fields(apps, schema_editor):
    Customer = apps.get_model('core', 'Customer')
    # 回滚操作：将所有客户的倍率字段设置回1.00
    Customer.objects.update(
        credit_card_multiplier=1.00,
        monthly_payment_multiplier=1.00
    )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_customer_monthly_payment_multiplier"),
    ]

    operations = [
        migrations.RunPython(reset_multiplier_fields, reverse_reset_multiplier_fields),
    ]
