# Generated by Django 4.2.24 on 2025-09-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_alter_customer_credit_card_multiplier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="monthly_payment_multiplier",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                default=0.002,
                max_digits=5,
                null=True,
                verbose_name="月供倍率",
            ),
        ),
    ]
