# Generated by Django 4.2.24 on 2025-10-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_alter_customer_monthly_payment_multiplier"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="is_archived",
            field=models.BooleanField(default=False, verbose_name="是否已归档"),
        ),
    ]
