# Generated by Django 4.2.24 on 2025-10-21 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_customer_is_archived"),
    ]

    operations = []
