# Generated by Django 4.2.24 on 2025-10-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_auto_20251021_1719"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerServicePhone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(max_length=100, verbose_name="银行/机构名称"),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=50, verbose_name="客服电话"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "客服电话",
                "verbose_name_plural": "客服电话",
                "ordering": ["bank_name"],
            },
        ),
    ]
